### ISSUE TITLE
rename mei2013to2015

### ISSUE THREAD

**Issue by pe-ro** [music-encoding/encoding-tools#1]
Since the latest release is no longer called '2015', the upgrade stylesheet mei2013to2015 should be renamed.  Andrew suggested mei21to30.xsl, which sounds good to me.

**Comment by bwbohl** [comment]
closed with bbed7f7adf4312135ba5cb81a00db16e45110eaa and b7e4cdd3612552f7053ed44a4e72805cd93c742d
