### ISSUE TITLE
mei30To40.xsl missing <history> to contain <provenance> in MEI 4

### ISSUE THREAD

**Issue by paul-bayleaf** [music-encoding/encoding-tools#27]
mei30To40.xsl converts MEI 3 &lt;physLoc&gt; &lt;provenance&gt;
into MEI 4                                &lt;physLoc&gt; &lt;provenance&gt;

But this is not legal MEI 4, it is missing &lt;history&gt; it should be:

&lt;physLoc&gt; &lt;history&gt; &lt;provenance&gt;

mei30To40.xsl contains code to add &lt;history&gt; in this case, but this does not appear to be working.  Attached before and after conversion, cut down from original MEI 3 as much as I can
[provenance.zip](https://github.com/music-encoding/encoding-tools/files/9250920/provenance.zip)

**Comment by musicEnfanthen** [comment]
@pe-ro Do you have any idea why `<history>` isn't included in the MEI4 conversion? Seems that the physLoc match block is never applied? (https://github.com/music-encoding/encoding-tools/blob/main/mei30To40/mei30To40.xsl#L1023-L1035)

**Comment by musicEnfanthen** [comment]
And, thank you, @paul-bayleaf, for catching this issue!

**Comment by musicEnfanthen** [comment]
Fixed in e3b84f8
